# Generated by Django 2.2.7 on 2019-11-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=100)),
                ('locktime', models.BigIntegerField()),
                ('lockDuration', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=100)),
                ('locktime', models.BigIntegerField()),
                ('lockDuration', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custid', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=100)),
                ('locktime', models.BigIntegerField()),
                ('lockDuration', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActiveUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdminStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=1)),
            ],
        ),
    ]
