#################################################################################
# DB Names
#################################################################################

VEHICLE_DB_NAME = "rent_cardb"
BOOKING_DB_NAME = "rent_rentaldb"
CUSTOMER_DB_NAME = "rent_customerdb"
EMPLOYEE_DB_NAME = "rent_employeedb"
USER_LOGIN_DB = "rent_adminstatus"
TIME_STAMP = "time_stamp"

#################################################################################
# Column Names
#################################################################################
VEHICLE_TYPE = "type"
VEHICLE_PROD_YEAR = "prod_year"
VEHICLE_BOOKED = "booked"
VEHICLE_LICENSE_PLATE = "license_plate"
VEHICLE_BRAND = "brand"
VEHICLE_MODEL = "model"
VEHICLE_COLOR = "color"

VEHICLE_COLUMN_LIST = (VEHICLE_TYPE, VEHICLE_PROD_YEAR, VEHICLE_BOOKED, VEHICLE_LICENSE_PLATE, VEHICLE_BRAND,
                       VEHICLE_MODEL, VEHICLE_COLOR,TIME_STAMP)

CUSTOMER_FIRST_NAME = "first_name"
CUSTOMER_LAST_NAME = "last_name"
CUSTOMER_PHONE_NO = "phone_no"
CUSTOMER_DRIVING_LICENSE = "driving_license"
CUSTOMER_LICENSE_EXPIRY = "expiry_date"

CUSTOMER_COLUMN_LIST = (
    CUSTOMER_FIRST_NAME, CUSTOMER_LAST_NAME, CUSTOMER_PHONE_NO, CUSTOMER_DRIVING_LICENSE, CUSTOMER_LICENSE_EXPIRY,TIME_STAMP)

BOOKING_ID = "booking_id"
BOOKING_START_DATE = "start_date"
BOOKING_END_DATE = "end_date"
BOOKING_STATUS = "booking_status"
BOOKING_DRIVING_LICENSE = CUSTOMER_DRIVING_LICENSE
BOOKING_LICENSE_PLATE = VEHICLE_LICENSE_PLATE

BOOKING_COLUMN_LIST = (BOOKING_DRIVING_LICENSE, BOOKING_END_DATE, BOOKING_START_DATE, BOOKING_LICENSE_PLATE,BOOKING_STATUS,TIME_STAMP)

EMPLOYEE_ID = "emp_id"
EMPLOYEE_FIRST_NAME = "first_name"
EMPLOYEE_LAST_NAME = "last_name"
EMPLOYEE_USER_NAME = "uname"
EMPLOYEE_PASSWORD = "password"
EMPLOYEE_TYPE = "type"

EMPLOYEE_COLUMN_LIST = (
    EMPLOYEE_ID, EMPLOYEE_FIRST_NAME, EMPLOYEE_LAST_NAME, EMPLOYEE_USER_NAME, EMPLOYEE_PASSWORD, EMPLOYEE_TYPE,TIME_STAMP)


LOGIN_STATUS = "stat"
##################################################################################
# Query Constants
##################################################################################

INSERT_QUERY_CAR_DB = "INSERT INTO " + VEHICLE_DB_NAME + str(VEHICLE_COLUMN_LIST) + "VALUES(?,?,?,?,?,?,?,?)"
UPDATE_QUERY_CAR_DB = "UPDATE " + VEHICLE_DB_NAME + " SET " + VEHICLE_TYPE + " = ? ," + VEHICLE_PROD_YEAR + " = ? ," + VEHICLE_BOOKED + " = ? ," + VEHICLE_LICENSE_PLATE + " = ? ," + VEHICLE_BRAND + " = ? ," + VEHICLE_MODEL + " = ? ," + VEHICLE_COLOR + " = ? ," + TIME_STAMP + " = ?" + " WHERE " + VEHICLE_LICENSE_PLATE + " = ?"
DELETE_QUERY_CAR_DB = "DELETE FROM " + VEHICLE_DB_NAME + " WHERE " + VEHICLE_LICENSE_PLATE + " = ?"
AVAILABLE_CARS_QUERY = "SELECT * FROM " + VEHICLE_DB_NAME + " WHERE " + VEHICLE_BOOKED + " = 0"

INSERT_QUERY_BOOKING_DB = "INSERT INTO " + BOOKING_DB_NAME + str(BOOKING_COLUMN_LIST) +  "VALUES(?,?,?,?,?,?)"
UPDATE_QUERY_BOOKING_DB = "UPDATE " + BOOKING_DB_NAME + " SET " + BOOKING_DRIVING_LICENSE + " = ? ," + BOOKING_END_DATE + " = ? ," + BOOKING_START_DATE + " = ? ," + BOOKING_LICENSE_PLATE+ " = ? ," + BOOKING_STATUS + " = ? ," + TIME_STAMP + " = ?" + " WHERE " + BOOKING_ID + " = ?"
DELETE_QUERY_BOOKING_DB = "DELETE FROM " + BOOKING_DB_NAME + " WHERE " + BOOKING_ID + " = ?"

INSERT_QUERY_CUSTOMER_DB = "INSERT INTO " + CUSTOMER_DB_NAME +  str(CUSTOMER_COLUMN_LIST) +  "VALUES(?,?,?,?,?,?)"
UPDATE_QUERY_CUSTOMER_DB = "UPDATE " + CUSTOMER_DB_NAME + " SET " + CUSTOMER_FIRST_NAME + " = ? ," + CUSTOMER_LAST_NAME + " = ? ," + CUSTOMER_PHONE_NO + " = ? ," + CUSTOMER_DRIVING_LICENSE + " = ? ," + CUSTOMER_LICENSE_EXPIRY + " = ? ," + TIME_STAMP + " = ?" + " WHERE " + CUSTOMER_DRIVING_LICENSE + " = ?"
DELETE_QUERY_CUSTOMER_DB = "DELETE FROM " + CUSTOMER_DB_NAME + " WHERE " + CUSTOMER_DRIVING_LICENSE + " = ?"

INSERT_QUERY_EMPLOYEE_DB = "INSERT INTO " + EMPLOYEE_DB_NAME + str(
    EMPLOYEE_COLUMN_LIST) + "VALUES(?,?,?,?,?,?,?)"
UPDATE_QUERY_EMPLOYEE_DB = "UPDATE " + EMPLOYEE_DB_NAME + " SET " + EMPLOYEE_ID + " = ? ," + EMPLOYEE_FIRST_NAME + " = ? ," + EMPLOYEE_LAST_NAME + " = ? ," + EMPLOYEE_USER_NAME + " = ? ," + EMPLOYEE_PASSWORD + " = ? ," + EMPLOYEE_TYPE + " = ? ," + TIME_STAMP + " = ?" + " WHERE " + EMPLOYEE_ID + " = ?"
DELETE_QUERY_EMPLOYEE_DB = "DELETE FROM " + EMPLOYEE_DB_NAME + " WHERE " + EMPLOYEE_ID + " = ?"

BOOKING_DATA_QUERY = "SELECT * from (" + BOOKING_DB_NAME + " INNER JOIN " + VEHICLE_DB_NAME + " on " + BOOKING_DB_NAME + "." + BOOKING_LICENSE_PLATE + " = " + VEHICLE_DB_NAME + "." + VEHICLE_LICENSE_PLATE + ") AS BookingData INNER JOIN " + CUSTOMER_DB_NAME + " on  BookingData." + BOOKING_DRIVING_LICENSE + " = " + CUSTOMER_DB_NAME + "." + CUSTOMER_DRIVING_LICENSE

LOGIN_STATUS_QUERY = "SELECT * FROM "+USER_LOGIN_DB
LOGIN_DELETE_QUERY = "DELETE FROM " + USER_LOGIN_DB